config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins|Rubik&display=swap" rel="stylesheet">

    <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NTPZ8FQ');</script>
<!-- End Google Tag Manager -->

  </head>

  <body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NTPZ8FQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->


        <%= render "partials/nav" %>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <%= yield %>

      <%= render "partials/pie" %>


  </body>
</html>

app/views/partials/_nav.html.erb
<nav>
    <div class="nav-wrapper">
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <%=link_to (image_tag("/images/sunn.png" , class:"logo") ),root_path , class:"brand-logo" %>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Inicio", root_path , class:"tituloBeneficio3"%> </li>
        <li><%= link_to "Retos", root_path , class:"tituloBeneficio3" %> </li>
        <li><%= link_to "Contacto", root_path , class:"tituloBeneficio3" %> </li>
        <li>



        <% if signed_in? %>
        <li>
          <span class="orange-text perfilTe"><%= current_user.email %></span>

          <%=link_to  (image_tag("/images/person.png" , class:"logo2") ),edit_user_registration_path , class:"brand-logo" %>
          <%= link_to "Perfil", edit_user_registration_path , class:"white-text btn logeo mostaza" %>
        </li>


        <li>
          <%=link_to  (image_tag("/images/close.png" , class:"logo2") ),new_user_session_path , class:"brand-logo" %>
          <%= link_to "Salir", destroy_user_session_path, method: :delete , class:"white-text btn logeo mostaza" %>
        </li>

         <% else %>
        <li>
          <%=link_to  (image_tag("/images/person.png" , class:"logo2") ),new_user_session_path , class:"brand-logo" %>
          <%= link_to "Ingresar", new_user_session_path , class:"white-text btn logeo mostaza" %>
        </li>
          <li>
            <%=link_to  (image_tag("/images/pencil.png" , class:"logo3") ),new_user_registration_path , class:"brand-logo" %>
            <%= link_to "Registrarse", new_user_registration_path , class:"white-text btn logeo mostaza" %>
          </li>
        <% end %>


      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><%= link_to "Inicio", root_path %> </li>
    <li><%= link_to "Inicio", root_path , class:"tituloBeneficio3"%> </li>
    <li><%= link_to "Retos", root_path , class:"tituloBeneficio3" %> </li>
    <li><%= link_to "Contacto", root_path , class:"tituloBeneficio3" %> </li>
    <li>
    <% if signed_in? %>
    <li>
      <span class="orange-text perfilTe"><%= current_user.email %></span>
      <%=link_to  (image_tag("/images/person.png" , class:"logo2") ),edit_user_registration_path , class:"brand-logo" %>
      <%= link_to "Perfil", edit_user_registration_path , class:"white-text btn logeo mostaza" %>
    </li>


    <li>
      <%=link_to  (image_tag("/images/close.png" , class:"logo2") ),new_user_session_path , class:"brand-logo" %>
      <%= link_to "Salir", destroy_user_session_path, method: :delete , class:"white-text btn logeo mostaza" %>
    </li>

     <% else %>
    <li>
      <%=link_to  (image_tag("/images/person.png" , class:"logo2") ),new_user_session_path , class:"brand-logo" %>
      <%= link_to "Ingresar", new_user_session_path , class:"white-text btn logeo mostaza" %>
    </li>
      <li>
        <%=link_to  (image_tag("/images/pencil.png" , class:"logo3") ),new_user_registration_path , class:"brand-logo" %>
        <%= link_to "Registrarse", new_user_registration_path , class:"white-text btn logeo mostaza" %>
      </li>
    <% end %>

  </ul>

app/views/partials/_pie.html.erb
<br><br>
<footer class="page-footer pie">
    <div class="container ">
      <div class="row">
        <div class="col s12 m5 l5 left">
            © 2019, SUNN Política de tratamiento de datos. www.rutan.co
        </div>
        <div class="col s12 m7 l7">
          <ul class="listadoPie">
            <li><a class="center" href="#!"><img src="/images/face.png" alt="" class="iconosPie "> <br> <h5 class="pieRedes">Noticias</h5> </a></li>
            <li><a class="center" href="#!"><img src="/images/twitter.png" alt="" class="iconosPie"><br> <h5 class="pieRedes">Contáctenos</h5></a></li>
            <li><a class="center" href="#!"><img src="/images/link.png" alt="" class="iconosPie"><br> <h5 class="pieRedes">Registrarse</h5></a></li>
            <li><a class="center" href="#!"><img src="/images/meseng.png" alt="" class="iconosPie"><br> <h5 class="pieRedes">Politicas de privacidad</h5></a></li>
          </ul>
        </div>
      </div>
    </div>

  </footer>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="col s12 m12 l12 ">
  <div class="rasco">
    <img src="/images/pex.jpg" alt="brain storm" class="inicio">
    <div class="parrafoInicial">
      <h1 class="white-text">Comunidad virtual de <br> innovación tecnológica</h1>
      <p class="white-text">Conectamos las ofertas con las demandas. Startup, inversionistas, empresas y grupos <br>
        de investigación y desarrollo en un mismo lugar. Registra tu empresa</p>
      <br>
      <%= link_to "Regístrarse", new_user_registration_path , class:"white-text btn logeo4 mostaza" %>

    </div>
  </div>


</div>
<div class="que  valign-wrapper">
  <div class="container">
    <div class="row ">
    <div class="center white-text">
      <h1 class="letraMostaza">¿Qué es Sunn?</h1>
      <p>SUNN, es una COMUNIDAD DE INNOVACIÓN VIRTUAL que permite a los usuarios comunicarse con otros
         ACTORES afines a sus capacidades o necesidades tecnológicas para generar conexiones estratégicas
         basadas en 5 grandes ecosistemas: Materiales Avanzados, Tecnologias Limpias, Energía, TIC´s, Ciencias de la Vida.
       </p>
   </div>
  </div>
 </div>
</div>
<div class="row">
  <div class="center">
    <h1 class="center blue-text">Beneficios</h1>
    <span >Tenemos ideas enfocadas para cada publico</span>
  </div>

<div class="col s12 m12 l12 listadoBeneficios">


    <div class="col s12 m3 l3 center  cajonBeneficio">
        <br>
      <img src="/images/tube.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio">Grupo de Investigacion y desarrollo</h2>
      <p>Si haces parte de un grupo de investigación y desarrollo: Convierte
        tus desarrollos en productos y servicios rentables.
        SUNN tiene para ti aliados estratégicos para ayudarte a potenciar tus investigaciones.
      </p>

    </div>
    <div class="col s12 m3 l3 center cajonBeneficio">
        <br>
      <img src="/images/avion.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio">Startups</h2>
      <p>Si haces parte de un grupo de investigación y desarrollo: Convierte
        tus desarrollos en productos y servicios rentables.
        SUNN tiene para ti aliados estratégicos para ayudarte a potenciar tus investigaciones.
      </p>

    </div>
    <div class="col s12 m3 l3 center cajonBeneficio">
        <br>
      <img src="/images/money.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio">Inversionistas</h2>
      <p>Si haces parte de un grupo de investigación y desarrollo: Convierte
        tus desarrollos en productos y servicios rentables.
        SUNN tiene para ti aliados estratégicos para ayudarte a potenciar tus investigaciones.
      </p>

    </div>
    <div class="col s12 m3 l3 center cajonBeneficio">
        <br>
      <img src="/images/maletin.png" alt="" class="beneficios">
      <br>
      <h2 class="tituloBeneficio">Empresas</h2>
      <p>Si haces parte de un grupo de investigación y desarrollo: Convierte
        tus desarrollos en productos y servicios rentables.
        SUNN tiene para ti aliados estratégicos para ayudarte a potenciar tus investigaciones.
      </p>

    </div>

  </div>



</div>

<div class="row contenedorSunn">
  <div class="col s0 m4 l4">
    <img src="/images/rocket.png" alt="" class="inicio">

  </div>
  <div class="col s12 m8 l8">
    <h2 class="tituloBeneficio ">Sunn pone a tu disposición excelentes <br>
      opciones para compartir en comunidad
    </h2>
    <div class="row ">
      <div class="col s6 m6 l6">

        <h3 class="tituloBeneficio"><i class="material-icons chequeoSunn white-text">check</i> Radar de Scouting</h3>
        <span>Explora , identifica y conecta <br>
          con actores de innovación y <br>
           necesidades de empresas.
        </span>

      </div>
      <div class="col s6 m6 l6">
        <h3 class="tituloBeneficio"><i class="material-icons chequeoSunn white-text">check</i> Salas de innovación</h3>
        <span>Interactúa con potenciales <br>
          aliados a través de mensajes.
        </span>

      </div>
    </div>
    <div class="row ">
      <div class="col s6 m6 l6">
        <h3 class="tituloBeneficio"><i class="material-icons chequeoSunn white-text">check</i> Referidos</h3>
        <span>Recomienda perfiles de <br>
          empresas y requerimientos a<br>
           otros amigos.
        </span>

      </div>
      <div class="col s6 m6 l6">
        <h3 class="tituloBeneficio"><i class="material-icons chequeoSunn white-text">check</i> Retos</h3>
        <span>Publica necesidades y retos <br>
          específicos o realiza <br>
          propuestas de solución a retos <br>
          existentes
        </span>

      </div>
      <div class=" col s12 m12 l12 center">
        <h5 class="tituloBeneficio2">Haz parte de la comunidad Sunn</h5>

         <%= link_to "Registrarse", new_user_registration_path , class:"btn mostaza regis"%>
      </div>
    </div>

  </div>
</div>

<div class="row ">
  <div class="center">
    <h1 class="tituloBeneficio">Retos</h1>
    <span>SUNN, tiene estos retos disponibles para ti</span>
    <br>  <br>

<div class="row">

      <div class="col s12 m4 l4 ">
        <div class="card">
          <div class="card-image">
              <img src="/images/city.jpg" alt="" class="">
          </div>
          <div class="card-content">
            <span class="card-title tituloBeneficio">Porsche Colombia SAS </span>
            <h6>¿Como involucro al cliente en una experiencia digital de servicio posventa?</h6>
            <p>Necesidad de contacto online y agilidad de agendamiento en el servicio post venta de vehiculos...
            </p>

            <br>
            <span><img src="/images/copa.png" alt="" class="retoLogo">Por Definir</span>
          </div>
          <div class="card-action">
            <%= link_to "Ver reto", new_user_registration_path , class:"btn verReto"%>
               <br>
               <ul class="listadoFehcas">
                 <li><a class="left"><span>Publicado: 2019-03-25</span></a>
                 </li>
                 <li><a class="right"><span>Cierra: 2019-05-26</span></a></li>
               </ul>


          </div>
        </div>
      </div>

      <div class="col s12 m4 l4">
        <div class="card">
          <div class="card-image">
              <img src="/images/moda.jpg" alt="" class="">
          </div>
          <div class="card-content">
            <span class="card-title tituloBeneficio">Mercadeo y Moda S.A.S Title</span>
            <h6>¿Como involucro al cliente en una experiencia digital de servicio posventa?</h6>
            <p>Necesidad de contacto online y agilidad de agendamiento en el servicio post venta de vehiculos...
            </p>

            <br>
            <span><img src="/images/copa.png" alt="" class="retoLogo">Por Definir</span>
          </div>
          <div class="card-action">
              <%= link_to "Ver reto", new_user_registration_path , class:"btn verReto"%>
              <br>
              <ul class="listadoFehcas">
                <li><a class="left"><span>Publicado: 2019-03-25</span></a>
                </li>
                <li><a class="right"><span>Cierra: 2019-05-26</span></a></li>
              </ul>
          </div>
        </div>
      </div>

      <div class="col s12 m4 l4">
        <div class="card">
          <div class="card-image">
              <img src="/images/transporte.jpg" alt="" class="">
          </div>
          <div class="card-content">
            <span class="card-title tituloBeneficio">Logistic Freight Solutions</span>
            <h6>¿Como involucro al cliente en una experiencia digital de servicio posventa?</h6>
            <p>
              Necesidad de contacto online y agilidad de agendamiento en el servicio post venta de vehiculos...
            </p>
            <br>
            <span><img src="/images/copa.png" alt="" class="retoLogo">Por Definir</span>
          </div>
          <div class="card-action">
            <%= link_to "Ver reto", new_user_registration_path , class:"btn verReto"%>
            <br>
            <div class="linksFechas">
              <ul class="listadoFehcas">
                <li><a class="left"><span>Publicado: 2019-03-25</span></a>
                </li>
                <li><a class="right"><span>Cierra: 2019-05-26</span></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
</div>


  </div>

</div>

<div class="row center">
  <%= link_to "Ver todos los retos", new_user_registration_path , class:"btn azulSunn regis"%>


</div>